
# throw
f() {
    try { hgferayfaer; }
    catch($e : OutOfRangeError){}
}

var t = $false
try {
    f
} catch($e) {
    $t = not $t
}
assert($t)
assert($? == 1)

# return
i() {
    if($false) {
        return 34
    }
    return 0
}

i
assert($? == 0)